[DEFAULT]
# KasterMethodsPath: Where is the Python file containing translation functions?
KasterMethodsPath = KAST/user_inputs/gotg/tb3_methods.py
# DataType: What type of parsing is required? (current options: 'csv', 'live')
DataType = live
# DataFile: If selected Parser requires a file source, put a path to it here
DataFile = none